<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE');
header('Access-Control-Allow-Headers: Content-Type, Authorization');
if (session_status() === PHP_SESSION_NONE) session_start();
require_once '../config.php';
require_once '../database.php';
require_once '../auth.php';
$db=new Database();$auth=new Auth($db);$pdo=$db->getConnection();
if(!$auth->isLoggedIn()){http_response_code(401);echo json_encode(['error'=>'غير مصرح بالوصول']);exit;}
$method=$_SERVER['REQUEST_METHOD'];$action=$_GET['action']??'';
try{switch($method){case 'GET':handleGetRequest($action,$pdo);break;case 'POST':handlePostRequest($action,$pdo);break;case 'PUT':handlePutRequest($action,$pdo);break;case 'DELETE':handleDeleteRequest($action,$pdo);break;default:http_response_code(405);echo json_encode(['error'=>'طريقة غير مدعومة']);}}catch(Exception $e){http_response_code(500);echo json_encode(['error'=>$e->getMessage()]);}
function handleGetRequest($action,$pdo){switch($action){case 'search':searchBaggage($pdo);break;case 'track':trackBaggage($pdo);break;case 'history':getTrackingHistory($pdo);break;case 'stats':getBaggageStats($pdo);break;case 'list':listBaggage($pdo);break;default:http_response_code(400);echo json_encode(['error'=>'إجراء غير صحيح']);}}
function handlePostRequest($action,$pdo){$input=json_decode(file_get_contents('php://input'),true);switch($action){case 'register':registerBaggage($pdo,$input);break;case 'update_status':updateBaggageStatus($pdo,$input);break;case 'add_tracking':addTrackingLog($pdo,$input);break;default:http_response_code(400);echo json_encode(['error'=>'إجراء غير صحيح']);}}
function handlePutRequest($action,$pdo){$input=json_decode(file_get_contents('php://input'),true);switch($action){case 'update':updateBaggage($pdo,$input);break;default:http_response_code(400);echo json_encode(['error'=>'إجراء غير صحيح']);}}
function handleDeleteRequest($action,$pdo){switch($action){case 'delete':deleteBaggage($pdo);break;default:http_response_code(400);echo json_encode(['error'=>'إجراء غير صحيح']);}}
function searchBaggage($pdo){$query=$_GET['q']??'';$type=$_GET['type']??'all';if(empty($query)){http_response_code(400);echo json_encode(['error'=>'كلمة البحث مطلوبة']);return;}$sql="SELECT b.*, u.full_name, u.passport_number, f.flight_number, f.departure_time, a1.airport_name as origin_airport, a2.airport_name as destination_airport, bt.type_name as baggage_type_name FROM baggage b JOIN users u ON b.passenger_id=u.id JOIN flights f ON b.flight_id=f.id JOIN airports a1 ON f.origin_airport_id=a1.id JOIN airports a2 ON f.destination_airport_id=a2.id JOIN baggage_types bt ON b.baggage_type_id=bt.id WHERE ";$p='%'.$query.'%';switch($type){case 'baggage_code':$sql.="b.baggage_code LIKE ?";break;case 'passenger_name':$sql.="u.full_name LIKE ?";break;case 'passport':$sql.="u.passport_number LIKE ?";break;case 'flight_number':$sql.="f.flight_number LIKE ?";break;default:$sql.="(b.baggage_code LIKE ? OR u.full_name LIKE ? OR u.passport_number LIKE ? OR f.flight_number LIKE ?)";}$sql.=" ORDER BY b.created_at DESC LIMIT 20";$stmt=$pdo->prepare($sql);$type==='all'?$stmt->execute([$p,$p,$p,$p]):$stmt->execute([$p]);$results=$stmt->fetchAll(PDO::FETCH_ASSOC);echo json_encode(['success'=>true,'data'=>$results,'count'=>count($results)]);}
function trackBaggage($pdo){$code=$_GET['code']??'';if(empty($code)){http_response_code(400);echo json_encode(['error'=>'رقم الحقيبة مطلوب']);return;}$stmt=$pdo->prepare("SELECT b.*,u.full_name,u.passport_number,f.flight_number,f.departure_time,f.arrival_time,a1.airport_name as origin_airport,a2.airport_name as destination_airport,bt.type_name as baggage_type_name FROM baggage b JOIN users u ON b.passenger_id=u.id JOIN flights f ON b.flight_id=f.id JOIN airports a1 ON f.origin_airport_id=a1.id JOIN airports a2 ON f.destination_airport_id=a2.id JOIN baggage_types bt ON b.baggage_type_id=bt.id WHERE b.baggage_code=?");$stmt->execute([$code]);$b=$stmt->fetch(PDO::FETCH_ASSOC);if(!$b){http_response_code(404);echo json_encode(['error'=>'لم يتم العثور على الأمتعة']);return;}$stmt=$pdo->prepare("SELECT tl.*,u.full_name as staff_name,l.location_name FROM tracking_logs tl LEFT JOIN users u ON tl.scanned_by=u.id LEFT JOIN locations l ON tl.location_id=l.id WHERE tl.baggage_id=? ORDER BY tl.actual_scan_time DESC");$stmt->execute([$b['id']]);echo json_encode(['success'=>true,'baggage'=>$b,'tracking_history'=>$stmt->fetchAll(PDO::FETCH_ASSOC)]);}
function getTrackingHistory($pdo){$id=$_GET['baggage_id']??'';if(empty($id)){http_response_code(400);echo json_encode(['error'=>'معرف الأمتعة مطلوب']);return;}$stmt=$pdo->prepare("SELECT tl.*,u.full_name as staff_name,l.location_name FROM tracking_logs tl LEFT JOIN users u ON tl.scanned_by=u.id LEFT JOIN locations l ON tl.location_id=l.id WHERE tl.baggage_id=? ORDER BY tl.actual_scan_time DESC");$stmt->execute([$id]);echo json_encode(['success'=>true,'data'=>$stmt->fetchAll(PDO::FETCH_ASSOC)]);}
function getBaggageStats($pdo){$period=$_GET['period']??'today';switch($period){case 'week':$dateCondition="created_at >= DATE_SUB(NOW(), INTERVAL 7 DAY)";break;case 'month':$dateCondition="created_at >= DATE_SUB(NOW(), INTERVAL 30 DAY)";break;default:$dateCondition="DATE(created_at)=CURDATE()";}$stats=[];$stats['total']=$pdo->query("SELECT COUNT(*) as total FROM baggage WHERE $dateCondition")->fetch()['total'];$stats['by_status']=$pdo->query("SELECT status,COUNT(*) as count FROM baggage WHERE $dateCondition GROUP BY status")->fetchAll(PDO::FETCH_ASSOC);$stats['delivered']=$pdo->query("SELECT COUNT(*) as delivered FROM baggage WHERE status='claimed' AND $dateCondition")->fetch()['delivered'];$stats['delayed']=$pdo->query("SELECT COUNT(*) as delayed FROM baggage WHERE status='delayed'")->fetch()['delayed'];$stats['lost']=$pdo->query("SELECT COUNT(*) as lost FROM baggage WHERE status='lost'")->fetch()['lost'];echo json_encode(['success'=>true,'data'=>$stats,'period'=>$period]);}
function listBaggage($pdo){$page=max(1,(int)($_GET['page']??1));$limit=max(1,min(100,(int)($_GET['limit']??20)));$status=$_GET['status']??'';$offset=($page-1)*$limit;$where='';$params=[];if($status!==''){$where="WHERE b.status = ?";$params[]=$status;}$sql="SELECT b.*,u.full_name,f.flight_number,bt.type_name as baggage_type_name FROM baggage b JOIN users u ON b.passenger_id=u.id JOIN flights f ON b.flight_id=f.id JOIN baggage_types bt ON b.baggage_type_id=bt.id $where ORDER BY b.created_at DESC LIMIT ? OFFSET ?";$params[]=$limit;$params[]=$offset;$stmt=$pdo->prepare($sql);$stmt->execute($params);$baggage=$stmt->fetchAll(PDO::FETCH_ASSOC);$count=$pdo->prepare("SELECT COUNT(*) as total FROM baggage b $where");$count->execute(array_slice($params,0,-2));$total=$count->fetch()['total'];echo json_encode(['success'=>true,'data'=>$baggage,'pagination'=>['page'=>$page,'limit'=>$limit,'total'=>$total,'pages'=>ceil($total/$limit)]]);}
function registerBaggage($pdo,$input){foreach(['passenger_id','flight_id','baggage_type_id','weight'] as $field){if(!isset($input[$field])||empty($input[$field])){http_response_code(400);echo json_encode(['error'=>"الحقل $field مطلوب"]);return;}}try{$code='BG'.date('Ymd').str_pad(rand(1,9999),4,'0',STR_PAD_LEFT);$stmt=$pdo->prepare("SELECT id FROM baggage WHERE baggage_code=?");$stmt->execute([$code]);while($stmt->fetch()){$code='BG'.date('Ymd').str_pad(rand(1,9999),4,'0',STR_PAD_LEFT);$stmt->execute([$code]);}$stmt=$pdo->prepare("SELECT fee_per_kg FROM baggage_types WHERE id=?");$stmt->execute([$input['baggage_type_id']]);$type=$stmt->fetch();$fee=$type['fee_per_kg']*$input['weight'];$stmt=$pdo->prepare("INSERT INTO baggage (baggage_code,passenger_id,flight_id,baggage_type_id,weight,length,width,height,color,brand,special_features,checkin_counter,checkin_staff_id,checkin_time,priority_level,fragile,special_handling,total_fee,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),?,?,?,?, 'checked_in')");$stmt->execute([$code,$input['passenger_id'],$input['flight_id'],$input['baggage_type_id'],$input['weight'],$input['length']??null,$input['width']??null,$input['height']??null,$input['color']??null,$input['brand']??null,$input['special_features']??null,'C'.rand(1,20),$_SESSION['user_id'],$input['priority_level']??'normal',$input['fragile']??0,$input['special_handling']??null,$fee]);$id=$pdo->lastInsertId();require_once '../functions_staff.php';$location=getOrCreateCheckinLocation($pdo);if(!$location){http_response_code(500);echo json_encode(['error'=>'Unable to get or create a checkin location.']);return;}$stmt=$pdo->prepare("INSERT INTO tracking_logs (baggage_id,location_id,status,scanned_by,scan_type) VALUES (?,?,'checked_in',?,'manual')");$stmt->execute([$id,$location,$_SESSION['user_id']]);echo json_encode(['success'=>true,'message'=>'تم تسجيل الأمتعة بنجاح','baggage_code'=>$code,'baggage_id'=>$id]);}catch(PDOException $e){http_response_code(500);echo json_encode(['error'=>'خطأ في تسجيل الأمتعة: '.$e->getMessage()]);}}
function updateBaggageStatus($pdo,$input){foreach(['baggage_id','status'] as $field){if(!isset($input[$field])||empty($input[$field])){http_response_code(400);echo json_encode(['error'=>"الحقل $field مطلوب"]);return;}}try{$stmt=$pdo->prepare("UPDATE baggage SET status=?, updated_at=CURRENT_TIMESTAMP WHERE id=?");$stmt->execute([$input['status'],$input['baggage_id']]);$location=$input['location_id']??null;if(!$location){require_once '../functions_staff.php';$location=getOrCreateCheckinLocation($pdo);}if(!$location){http_response_code(500);echo json_encode(['error'=>'Unable to get or create a checkin location.']);return;}$stmt=$pdo->prepare("INSERT INTO tracking_logs (baggage_id,location_id,status,remarks,scanned_by,scan_type,actual_scan_time) VALUES (?,?,?,?,?,?,NOW())");$stmt->execute([$input['baggage_id'],$location,$input['status'],$input['remarks']??'',$_SESSION['user_id'],$input['scan_type']??'manual']);echo json_encode(['success'=>true,'message'=>'تم تحديث حالة الأمتعة بنجاح']);}catch(PDOException $e){http_response_code(500);echo json_encode(['error'=>'خطأ في تحديث حالة الأمتعة: '.$e->getMessage()]);}}
function addTrackingLog($pdo,$input){foreach(['baggage_id','status'] as $field){if(!isset($input[$field])||empty($input[$field])){http_response_code(400);echo json_encode(['error'=>"الحقل $field مطلوب"]);return;}}try{$location=$input['location_id']??null;if(!$location){require_once '../functions_staff.php';$location=getOrCreateCheckinLocation($pdo);}if(!$location){http_response_code(500);echo json_encode(['error'=>'Unable to get or create a checkin location.']);return;}$stmt=$pdo->prepare("INSERT INTO tracking_logs (baggage_id,location_id,status,remarks,scanned_by,scan_type,actual_scan_time) VALUES (?,?,?,?,?,?,NOW())");$stmt->execute([$input['baggage_id'],$location,$input['status'],$input['remarks']??'',$_SESSION['user_id'],$input['scan_type']??'manual']);echo json_encode(['success'=>true,'message'=>'تم إضافة سجل التتبع بنجاح']);}catch(PDOException $e){http_response_code(500);echo json_encode(['error'=>'خطأ في إضافة سجل التتبع: '.$e->getMessage()]);}}
function updateBaggage($pdo,$input){if(!isset($input['baggage_id'])){http_response_code(400);echo json_encode(['error'=>'معرف الأمتعة مطلوب']);return;}try{$fields=['weight','length','width','height','color','brand','special_features','priority_level','fragile','special_handling'];$updates=[];$values=[];foreach($fields as $field){if(isset($input[$field])){$updates[]="$field = ?";$values[]=$input[$field];}}if(empty($updates)){http_response_code(400);echo json_encode(['error'=>'لا توجد حقول للتحديث']);return;}$values[]=$input['baggage_id'];$stmt=$pdo->prepare("UPDATE baggage SET ".implode(', ',$updates).", updated_at=CURRENT_TIMESTAMP WHERE id=?");$stmt->execute($values);echo json_encode(['success'=>true,'message'=>'تم تحديث بيانات الأمتعة بنجاح']);}catch(PDOException $e){http_response_code(500);echo json_encode(['error'=>'خطأ في تحديث بيانات الأمتعة: '.$e->getMessage()]);}}
function deleteBaggage($pdo){$id=$_GET['id']??'';if(empty($id)){http_response_code(400);echo json_encode(['error'=>'معرف الأمتعة مطلوب']);return;}try{$stmt=$pdo->prepare("DELETE FROM baggage WHERE id=?");$stmt->execute([$id]);echo json_encode(['success'=>true,'message'=>'تم حذف الأمتعة بنجاح']);}catch(PDOException $e){http_response_code(500);echo json_encode(['error'=>'خطأ في حذف الأمتعة: '.$e->getMessage()]);}}
?>