<?php
header('Content-Type: application/json');header('Access-Control-Allow-Origin: *');header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE');header('Access-Control-Allow-Headers: Content-Type, Authorization');
if(session_status()===PHP_SESSION_NONE)session_start();require_once '../config.php';require_once '../database.php';require_once '../auth.php';$db=new Database();$auth=new Auth($db);$pdo=$db->getConnection();if(!$auth->isLoggedIn()){http_response_code(401);echo json_encode(['error'=>'غير مصرح بالوصول']);exit;}$method=$_SERVER['REQUEST_METHOD'];$action=$_GET['action']??'';
try{switch($method){case 'GET':handleGetRequest($action,$pdo);break;case 'POST':handlePostRequest($action,$pdo);break;case 'PUT':handlePutRequest($action,$pdo);break;case 'DELETE':handleDeleteRequest($action,$pdo);break;default:http_response_code(405);echo json_encode(['error'=>'طريقة غير مدعومة']);}}catch(Exception $e){http_response_code(500);echo json_encode(['error'=>$e->getMessage()]);}
function handleGetRequest($a,$pdo){switch($a){case 'list':getNotifications($pdo);break;case 'unread':getUnreadNotifications($pdo);break;case 'count':getNotificationCount($pdo);break;case 'templates':getNotificationTemplates($pdo);break;default:http_response_code(400);echo json_encode(['error'=>'إجراء غير صحيح']);}}
function handlePostRequest($a,$pdo){$i=json_decode(file_get_contents('php://input'),true);switch($a){case 'send':sendNotification($pdo,$i);break;case 'send_bulk':sendBulkNotification($pdo,$i);break;case 'create_template':createNotificationTemplate($pdo,$i);break;default:http_response_code(400);echo json_encode(['error'=>'إجراء غير صحيح']);}}
function handlePutRequest($a,$pdo){$i=json_decode(file_get_contents('php://input'),true);switch($a){case 'mark_read':markNotificationAsRead($pdo,$i);break;case 'mark_all_read':markAllNotificationsAsRead($pdo);break;case 'update_template':updateNotificationTemplate($pdo,$i);break;default:http_response_code(400);echo json_encode(['error'=>'إجراء غير صحيح']);}}
function handleDeleteRequest($a,$pdo){switch($a){case 'delete':deleteNotification($pdo);break;case 'delete_template':deleteNotificationTemplate($pdo);break;default:http_response_code(400);echo json_encode(['error'=>'إجراء غير صحيح']);}}
function getNotifications($pdo){$uid=$_SESSION['user_id'];$page=max(1,(int)($_GET['page']??1));$limit=max(1,min(100,(int)($_GET['limit']??20)));$type=$_GET['type']??'';$status=$_GET['status']??'';$offset=($page-1)*$limit;$where='WHERE user_id = ?';$p=[$uid];if($type!==''){$where.=' AND type = ?';$p[]=$type;}if($status!==''){$where.=' AND status = ?';$p[]=$status;}$sql="SELECT * FROM notifications $where ORDER BY created_at DESC LIMIT ? OFFSET ?";$p[]=$limit;$p[]=$offset;$s=$pdo->prepare($sql);$s->execute($p);$rows=$s->fetchAll(PDO::FETCH_ASSOC);$c=$pdo->prepare("SELECT COUNT(*) as total FROM notifications $where");$c->execute(array_slice($p,0,-2));$total=$c->fetch()['total'];echo json_encode(['success'=>true,'data'=>$rows,'pagination'=>['page'=>$page,'limit'=>$limit,'total'=>$total,'pages'=>ceil($total/$limit)]]);}
function getUnreadNotifications($pdo){$limit=max(1,min(100,(int)($_GET['limit']??10)));$s=$pdo->prepare("SELECT * FROM notifications WHERE user_id = ? AND status IN ('pending','sent','delivered') ORDER BY created_at DESC LIMIT ?");$s->execute([$_SESSION['user_id'],$limit]);echo json_encode(['success'=>true,'data'=>$s->fetchAll(PDO::FETCH_ASSOC)]);}
function getNotificationCount($pdo){$s=$pdo->prepare("SELECT COUNT(*) as count FROM notifications WHERE user_id = ? AND status IN ('pending','sent','delivered')");$s->execute([$_SESSION['user_id']]);echo json_encode(['success'=>true,'count'=>$s->fetch()['count']]);}
function getNotificationTemplates($pdo){$s=$pdo->query("SELECT * FROM email_templates WHERE status='active' ORDER BY template_name");echo json_encode(['success'=>true,'data'=>$s->fetchAll(PDO::FETCH_ASSOC)]);}
function sendNotification($pdo,$i){foreach(['user_id','type','title','message'] as $f){if(!isset($i[$f])||empty($i[$f])){http_response_code(400);echo json_encode(['error'=>"الحقل $f مطلوب"]);return;}}try{$s=$pdo->prepare("INSERT INTO notifications (user_id,type,title,message,action_url,channels,priority,status,metadata,created_at) VALUES (?,?,?,?,?,?,?,'pending',?,NOW())");$channels=json_encode($i['channels']??['in_app']);$meta=json_encode($i['metadata']??[]);$s->execute([$i['user_id'],$i['type'],$i['title'],$i['message'],$i['action_url']??null,$channels,$i['priority']??'medium',$meta]);$id=$pdo->lastInsertId();sendNotificationChannels($i,$channels);echo json_encode(['success'=>true,'message'=>'تم إرسال الإشعار بنجاح','notification_id'=>$id]);}catch(PDOException $e){http_response_code(500);echo json_encode(['error'=>'خطأ في إرسال الإشعار: '.$e->getMessage()]);}}
function sendBulkNotification($pdo,$i){foreach(['user_ids','type','title','message'] as $f){if(!isset($i[$f])||empty($i[$f])){http_response_code(400);echo json_encode(['error'=>"الحقل $f مطلوب"]);return;}}if(!is_array($i['user_ids'])){http_response_code(400);echo json_encode(['error'=>'user_ids يجب أن يكون مصفوفة']);return;}try{$pdo->beginTransaction();$channels=json_encode($i['channels']??['in_app']);$meta=json_encode($i['metadata']??[]);$s=$pdo->prepare("INSERT INTO notifications (user_id,type,title,message,action_url,channels,priority,status,metadata,created_at) VALUES (?,?,?,?,?,?,?,'pending',?,NOW())");$count=0;foreach($i['user_ids'] as $uid){$s->execute([$uid,$i['type'],$i['title'],$i['message'],$i['action_url']??null,$channels,$i['priority']??'medium',$meta]);$count++;}$pdo->commit();echo json_encode(['success'=>true,'message'=>"تم إرسال الإشعار إلى $count مستخدم",'sent_count'=>$count]);}catch(PDOException $e){if($pdo->inTransaction())$pdo->rollBack();http_response_code(500);echo json_encode(['error'=>'خطأ في إرسال الإشعار الجماعي: '.$e->getMessage()]);}}
function createNotificationTemplate($pdo,$i){foreach(['template_code','template_name','subject','body_content'] as $f){if(!isset($i[$f])||empty($i[$f])){http_response_code(400);echo json_encode(['error'=>"الحقل $f مطلوب"]);return;}}try{$s=$pdo->prepare("INSERT INTO email_templates (template_code,template_name,subject,body_content,variables,status,created_at) VALUES (?,?,?,?,?,'active',NOW())");$s->execute([$i['template_code'],$i['template_name'],$i['subject'],$i['body_content'],json_encode($i['variables']??[])]);echo json_encode(['success'=>true,'message'=>'تم إنشاء القالب بنجاح','template_id'=>$pdo->lastInsertId()]);}catch(PDOException $e){http_response_code(500);echo json_encode(['error'=>'خطأ في إنشاء القالب: '.$e->getMessage()]);}}
function markNotificationAsRead($pdo,$i){if(!isset($i['notification_id'])){http_response_code(400);echo json_encode(['error'=>'معرف الإشعار مطلوب']);return;}try{$s=$pdo->prepare("UPDATE notifications SET status='read',read_at=NOW() WHERE id=? AND user_id=?");$s->execute([$i['notification_id'],$_SESSION['user_id']]);if($s->rowCount()>0)echo json_encode(['success'=>true,'message'=>'تم تحديد الإشعار كمقروء']);else{http_response_code(404);echo json_encode(['error'=>'لم يتم العثور على الإشعار']);}}catch(PDOException $e){http_response_code(500);echo json_encode(['error'=>'خطأ في تحديث الإشعار: '.$e->getMessage()]);}}
function markAllNotificationsAsRead($pdo){try{$s=$pdo->prepare("UPDATE notifications SET status='read',read_at=NOW() WHERE user_id=? AND status IN ('pending','sent','delivered')");$s->execute([$_SESSION['user_id']]);echo json_encode(['success'=>true,'message'=>'تم تحديد '.$s->rowCount().' إشعار كمقروء']);}catch(PDOException $e){http_response_code(500);echo json_encode(['error'=>'خطأ في تحديث الإشعارات: '.$e->getMessage()]);}}
function updateNotificationTemplate($pdo,$i){if(!isset($i['template_id'])){http_response_code(400);echo json_encode(['error'=>'معرف القالب مطلوب']);return;}try{$fields=['template_name','subject','body_content','variables','status'];$u=[];$v=[];foreach($fields as $f){if(isset($i[$f])){$u[]="$f = ?";$v[]=$f==='variables'?json_encode($i[$f]):$i[$f];}}if(!$u){http_response_code(400);echo json_encode(['error'=>'لا توجد حقول للتحديث']);return;}$v[]=$i['template_id'];$s=$pdo->prepare("UPDATE email_templates SET ".implode(', ',$u).", updated_at=NOW() WHERE id=?");$s->execute($v);if($s->rowCount()>0)echo json_encode(['success'=>true,'message'=>'تم تحديث القالب بنجاح']);else{http_response_code(404);echo json_encode(['error'=>'لم يتم العثور على القالب']);}}catch(PDOException $e){http_response_code(500);echo json_encode(['error'=>'خطأ في تحديث القالب: '.$e->getMessage()]);}}
function deleteNotification($pdo){$id=$_GET['id']??'';if(empty($id)){http_response_code(400);echo json_encode(['error'=>'معرف الإشعار مطلوب']);return;}try{$s=$pdo->prepare("DELETE FROM notifications WHERE id=? AND user_id=?");$s->execute([$id,$_SESSION['user_id']]);if($s->rowCount()>0)echo json_encode(['success'=>true,'message'=>'تم حذف الإشعار بنجاح']);else{http_response_code(404);echo json_encode(['error'=>'لم يتم العثور على الإشعار']);}}catch(PDOException $e){http_response_code(500);echo json_encode(['error'=>'خطأ في حذف الإشعار: '.$e->getMessage()]);}}
function deleteNotificationTemplate($pdo){$id=$_GET['id']??'';if(empty($id)){http_response_code(400);echo json_encode(['error'=>'معرف القالب مطلوب']);return;}try{$s=$pdo->prepare("DELETE FROM email_templates WHERE id=?");$s->execute([$id]);if($s->rowCount()>0)echo json_encode(['success'=>true,'message'=>'تم حذف القالب بنجاح']);else{http_response_code(404);echo json_encode(['error'=>'لم يتم العثور على القالب']);}}catch(PDOException $e){http_response_code(500);echo json_encode(['error'=>'خطأ في حذف القالب: '.$e->getMessage()]);}}
function sendNotificationChannels($i,$channels){foreach(json_decode($channels,true) as $c){switch($c){case 'email':sendEmailNotification($i);break;case 'sms':sendSMSNotification($i);break;case 'push':sendPushNotification($i);break;}}}
function sendEmailNotification($i){error_log('Email notification sent: '.$i['title']);}
function sendSMSNotification($i){error_log('SMS notification sent: '.$i['title']);}
function sendPushNotification($i){error_log('Push notification sent: '.$i['title']);}
?>