<?php
if (session_status() === PHP_SESSION_NONE) session_start();
$loggedIn = !empty($_SESSION['logged_in']);
$role = $_SESSION['user_role'] ?? null;
$dashboard = 'pages/login.php';
if ($loggedIn) {
    if (in_array($role, ['system_admin','airline_manager'])) $dashboard='admin/dashboard.php';
    elseif (in_array($role, ['supervisor','handling_staff','counter_staff'])) $dashboard='staff/dashboard.php';
    elseif ($role==='passenger') $dashboard='passenger/dashboard.php';
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Smart Baggage Tracking System</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"><style>body{background:linear-gradient(135deg,#667eea,#764ba2);min-height:100vh;color:#fff}.hero{min-height:100vh;display:flex;align-items:center}.cardx{background:rgba(255,255,255,.12);backdrop-filter:blur(8px);border-radius:1rem;padding:2rem}.feature{background:#fff;color:#222;border-radius:1rem;padding:1.25rem;height:100%}</style></head><body><main class="hero"><div class="container"><div class="row align-items-center g-4"><div class="col-lg-7"><h1 class="display-4 fw-bold"><i class="fas fa-suitcase-rolling"></i> Smart Baggage Tracking</h1><p class="lead">A web-based airport baggage management and tracking prototype for passengers, staff and administrators.</p><a class="btn btn-light btn-lg me-2" href="<?=htmlspecialchars($dashboard)?>"><?=$loggedIn?'Open Dashboard':'Login'?></a><?php if(!$loggedIn):?><a class="btn btn-outline-light btn-lg" href="pages/register.php">Create Account</a><?php endif;?></div><div class="col-lg-5"><div class="cardx"><h3>System modules</h3><ul class="mb-0"><li>Passenger baggage tracking</li><li>Staff check-in and tracking updates</li><li>Flight management</li><li>Administration and analytics</li><li>Notifications, support and quality reports</li></ul></div></div></div><div class="row g-3 mt-4"><div class="col-md-4"><div class="feature"><i class="fas fa-location-dot text-primary fs-2"></i><h5 class="mt-2">Track</h5><p>Follow baggage status and location history.</p></div></div><div class="col-md-4"><div class="feature"><i class="fas fa-users-gear text-success fs-2"></i><h5 class="mt-2">Role-based access</h5><p>Separate passenger, staff and admin workflows.</p></div></div><div class="col-md-4"><div class="feature"><i class="fas fa-chart-line text-warning fs-2"></i><h5 class="mt-2">Operations</h5><p>Reports, flight status and operational dashboards.</p></div></div></div></div></main></body></html>